Update testnew-report.yml

diff --git a/testnew-report.yml b/testnew-report.yml
--- a/testnew-report.yml
+++ b/testnew-report.yml
@@ -16,7 +16,7 @@
         state: directory
         mode: '0755'
 
-    - name: Start HTML table report
+    - name: Start HTML report with horizontal layout
       copy:
         content: |
           <html>
@@ -39,101 +39,61 @@
           </head>
           <body>
           <table>
-          <tr><th>Section</th><th>Details</th></tr>
+          <tr>
+            <th>Hostname</th>
+            <th>IP Address</th>
+            <th>Uptime</th>
+            <th>Processors</th>
+            <th>Memory</th>
+            <th>Kernel Version</th>
+            <th>Datadog</th>
+            <th>Netdata</th>
+            <th>Open Ports</th>
+            <th>Filesystems</th>
+            <th>NFS/CIFS</th>
+            <th>Crontab</th>
+            <th>Top Memory</th>
+            <th>Top CPU</th>
+            <th>Last Logins</th>
+            <th>Last Patch</th>
+          </tr>
+          <tr>
         dest: "{{ src_path }}/report.html"
 
-    - name: Add hostname and IP
+    - name: Gather system information and append to HTML row
       shell: |
-        echo "<tr><td>Hostname</td><td>$(hostname)</td></tr>" >> {{ src_path }}/report.html
-        echo "<tr><td>IP Address</td><td>$(hostname -I)</td></tr>" >> {{ src_path }}/report.html
-
-    - name: Add uptime
-      shell: |
-        echo "<tr><td>Uptime</td><td>$(uptime)</td></tr>" >> {{ src_path }}/report.html
-
-    - name: Add number of processors
-      shell: |
-        echo "<tr><td>Processors</td><td>$(nproc)</td></tr>" >> {{ src_path }}/report.html
-
-    - name: Add memory info
-      shell: |
+        echo -n "<td>$(hostname)</td>" >> {{ src_path }}/report.html
+        echo -n "<td>$(hostname -I)</td>" >> {{ src_path }}/report.html
+        echo -n "<td>$(uptime)</td>" >> {{ src_path }}/report.html
+        echo -n "<td>$(nproc)</td>" >> {{ src_path }}/report.html
         mem=$(free -h | awk '/Mem:/ {print $2 " total, " $3 " used, " $4 " free"}')
-        echo "<tr><td>Memory</td><td>${mem}</td></tr>" >> {{ src_path }}/report.html
-
-    - name: Add kernel version
-      shell: |
-        echo "<tr><td>Kernel Version</td><td>$(uname -r)</td></tr>" >> {{ src_path }}/report.html
-
-    - name: Add Datadog agent status
-      shell: |
-        systemctl is-active datadog-agent &>/dev/null && echo "<tr><td>Datadog Agent</td><td>Installed and Running</td></tr>" || echo "<tr><td>Datadog Agent</td><td>Not Found</td></tr>"
-        >> {{ src_path }}/report.html
-
-    - name: Add Netdata agent status
-      shell: |
-        systemctl is-active netdata &>/dev/null && echo "<tr><td>Netdata Agent</td><td>Installed and Running</td></tr>" || echo "<tr><td>Netdata Agent</td><td>Not Found</td></tr>"
-        >> {{ src_path }}/report.html
-
-    - name: Check selected active services
-      shell: |
-        for svc in nfs-server smb cups cups.service auditd kdump chronyd netdata postfix \
-                   rpc-statd-notify rpcbind rsyslog snmpd sshd systemd-journald winbind; do
-          state=$(systemctl is-active $svc 2>/dev/null)
-          desc=$(systemctl show -p Description $svc 2>/dev/null | cut -d= -f2)
-          [[ "$state" == "active" ]] && echo "<tr><td>$svc</td><td>${desc}</td></tr>" || :
-        done >> {{ src_path }}/report.html
-
-    - name: List open ports with service description
-      shell: |
-        echo "<tr><td>Open Ports</td><td><pre>" >> {{ src_path }}/report.html
-        nmap -sT -p- --min-rate=1000 -T4 localhost | grep -E "open" >> {{ src_path }}/report.html
-        echo "</pre></td></tr>" >> {{ src_path }}/report.html
-
-    - name: Add filesystem info
-      shell: |
-        echo "<tr><td>Filesystems</td><td><pre>" >> {{ src_path }}/report.html
-        df -h --exclude-type=tmpfs --exclude-type=devtmpfs --exclude-type=nfs --exclude-type=cifs >> {{ src_path }}/report.html
-        echo "</pre></td></tr>" >> {{ src_path }}/report.html
-
-    - name: Add NFS/CIFS mounts
-      shell: |
-        echo "<tr><td>NFS/CIFS Mounts</td><td><pre>" >> {{ src_path }}/report.html
-        df -hT | grep -E 'nfs|cifs' || echo "No NFS/CIFS mounts found" >> {{ src_path }}/report.html
-        echo "</pre></td></tr>" >> {{ src_path }}/report.html
-
-    - name: Add crontab jobs
-      shell: |
-        echo "<tr><td>Crontab</td><td><pre>" >> {{ src_path }}/report.html
-        crontab -l || echo "No crontab for root" >> {{ src_path }}/report.html
-        echo "</pre></td></tr>" >> {{ src_path }}/report.html
-
-    - name: Add top memory consumers
-      shell: |
-        echo "<tr><td>Top Memory Usage</td><td><pre>" >> {{ src_path }}/report.html
-        ps aux --sort=-%mem | head -n 8 >> {{ src_path }}/report.html
-        echo "</pre></td></tr>" >> {{ src_path }}/report.html
-
-    - name: Add top CPU consumers
-      shell: |
-        echo "<tr><td>Top CPU Usage</td><td><pre>" >> {{ src_path }}/report.html
-        ps aux --sort=-%cpu | head -n 8 >> {{ src_path }}/report.html
-        echo "</pre></td></tr>" >> {{ src_path }}/report.html
-
-    - name: Add last logins
-      shell: |
-        echo "<tr><td>Last 7 Logins</td><td><pre>" >> {{ src_path }}/report.html
-        last -n 7 >> {{ src_path }}/report.html
-        echo "</pre></td></tr>" >> {{ src_path }}/report.html
-
-    - name: Check last patch info
-      shell: |
-        echo "<tr><td>Last Patch Info</td><td><pre>" >> {{ src_path }}/report.html
-        dnf history | grep update >> {{ src_path }}/report.html
-        echo "</pre></td></tr>" >> {{ src_path }}/report.html
+        echo -n "<td>${mem}</td>" >> {{ src_path }}/report.html
+        echo -n "<td>$(uname -r)</td>" >> {{ src_path }}/report.html
+        datadog=$(systemctl is-active datadog-agent &>/dev/null && echo "Running" || echo "Not Found")
+        echo -n "<td>${datadog}</td>" >> {{ src_path }}/report.html
+        netdata=$(systemctl is-active netdata &>/dev/null && echo "Running" || echo "Not Found")
+        echo -n "<td>${netdata}</td>" >> {{ src_path }}/report.html
+        ports=$(nmap -sT -p- --min-rate=1000 -T4 localhost | grep -E "open" | tr '\n' ' ')
+        echo -n "<td><pre>${ports}</pre></td>" >> {{ src_path }}/report.html
+        fs=$(df -h --exclude-type=tmpfs --exclude-type=devtmpfs --exclude-type=nfs --exclude-type=cifs | tr '\n' ' ')
+        echo -n "<td><pre>${fs}</pre></td>" >> {{ src_path }}/report.html
+        nfscifs=$(df -hT | grep -E 'nfs|cifs' | tr '\n' ' ')
+        [[ -z "$nfscifs" ]] && nfscifs="No NFS/CIFS" 
+        echo -n "<td><pre>${nfscifs}</pre></td>" >> {{ src_path }}/report.html
+        crontab=$(crontab -l 2>/dev/null || echo "No crontab")
+        echo -n "<td><pre>${crontab}</pre></td>" >> {{ src_path }}/report.html
+        topmem=$(ps aux --sort=-%mem | head -n 8 | tr '\n' ' ')
+        echo -n "<td><pre>${topmem}</pre></td>" >> {{ src_path }}/report.html
+        topcpu=$(ps aux --sort=-%cpu | head -n 8 | tr '\n' ' ')
+        echo -n "<td><pre>${topcpu}</pre></td>" >> {{ src_path }}/report.html
+        logins=$(last -n 7 | tr '\n' ' ')
+        echo -n "<td><pre>${logins}</pre></td>" >> {{ src_path }}/report.html
+        patch=$(dnf history | grep update | tr '\n' ' ')
+        echo "<td><pre>${patch}</pre></td>" >> {{ src_path }}/report.html
 
     - name: Close HTML table and body
       shell: |
-        echo "</table></body></html>" >> {{ src_path }}/report.html
+        echo "</tr></table></body></html>" >> {{ src_path }}/report.html
 
     - name: Create local directory with the current date
       file:
